version: '3.8'

services:
  jenkins:
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    container_name: jenkins
    user: root  # Run as root to access Docker socket
    command: >
      sh -c "
      usermod -aG docker jenkins &&
      chmod 666 /var/run/docker.sock &&
      su jenkins -c '/usr/bin/tini -- /usr/local/bin/jenkins.sh'
      "

volumes:
  jenkins-data: